---
title: "Intro to Survey Data"
format: html
---

```{r}
#| warnings: false
#| echo: false

library(qualtRics)
library(tidyr)
library(knitr)
library(ggplot2)
library(kableExtra)
library(dplyr)
```

## Connect to Qualtrics API
```{r}
# qualtrics_api_credentials(api_key = "Insert API key",
#                          base_url = "ucsb.co1.qualtrics.com", install = TRUE,
#                          overwrite = T)
```

## Get all surveys
```{r}
surveys <- all_surveys()
```

## Saving survey id
```{r}
i <- which(surveys$name == "Survey for Data Science Training")

id <- surveys$id[i]
```

## List of questions
```{r}
questions <- survey_questions(id)

kable(questions) %>% 
  kable_styling()
```

## Get survey results
```{r}
survey_results <- fetch_survey(id)
```

## Clean results
### Question 2
```{r}
q2 <- survey_results %>% 
  select(Q2) %>% 
  group_by(Q2) %>% # groups by all the options in the multiple choice Q
  summarise(n = n())

kable(q2, col.names = c("How long have you been programming?",
                        "Number of responses")) %>% 
  kable_styling()
```

### Question 3
```{r}
q3 <- survey_results %>% 
  select(Q3) %>% 
  group_by(Q3) %>% 
  summarise(n = n())

ggplot(q3, aes(x = Q3, y = n))+
  geom_col()+
  labs(x = "What language do you currently use most frequently?",
       y = "Number of responses")+
  theme_bw()
```

Open-response text
```{r}
q3_text <- survey_results %>% 
  select(Q3_7_TEXT) %>% 
  drop_na()

kable(q3_text, col.names = "Other Responses to 'What language do you currently use most frequently?'") %>% 
  kable_styling()
```

### Question 4
```{r}
q4 <- survey_results %>% 
  select(Q4) %>% 
  rename("What data science tool or language are you most excited to learn?" = Q4) %>% 
  drop_na()

kable(q4) %>% 
  kable_styling()
```

